name: Automated Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_groups:
        description: 'Test groups to run'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - e2e
          - ui
          - regression
          - all

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-group:
          - ${{ github.event.inputs.test_groups || 'smoke' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: |
          if [ "${{ matrix.test-group }}" == "all" ]; then
            ./gradlew clean test
          else
            ./gradlew clean test -Dgroups=${{ matrix.test-group }}
          fi

      - name: Generate Allure Report
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
          unzip allure-2.27.0.zip
          ./allure-2.27.0/bin/allure generate build/allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: matrix-allure-report
          path: allure-report/
